name: Deploy Admin Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            echo "ğŸ“‚ Go to admin frontend repo"
            cd /home/ec2-user/assist-health/users-backend-main

            echo "â¬‡ Pull latest code"
            git pull origin main

            echo "ğŸ³ Build & restart admin frontend"
            cd /home/ec2-user/assist-health
            docker compose -f docker-compose.users.yml build users_backend
            docker compose -f docker-compose.users.yml up -d --build users_backend
          # script: |
          #   rsync -av --delete $GITHUB_WORKSPACE/ ~/assist-health/users-backend-main/
          #   cd ~/assist-health
          #   docker compose -f docker-compose.admin.yml build users_backend
          #   docker compose -f docker-compose.admin.yml up -d users_backend
          
